# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXr7ETgYNrFok0Fii3W68iS-gm_wqqwC
"""

import streamlit as st
import pandas as pd
import joblib

# تحميل الموديل مباشرة من نفس الفولدر
model = joblib.load("final_model.pkl")

# دالة لتحويل الإدخال raw → one-hot
def encode_input(raw_dict):
    encoded = {}
    for col in ["age","trestbps","chol","thalach","oldpeak"]:
        encoded[col] = raw_dict[col]

    encoded[f"sex_{raw_dict['sex']}.0"] = 1
    encoded[f"exang_{raw_dict['exang']}.0"] = 1
    encoded[f"fbs_{raw_dict['fbs']}.0"] = 1
    encoded[f"cp_{raw_dict['cp']}.0"] = 1
    encoded[f"restecg_{raw_dict['restecg']}.0"] = 1
    encoded[f"slope_{raw_dict['slope']}.0"] = 1
    encoded[f"ca_{raw_dict['ca']}.0"] = 1
    encoded[f"thal_{raw_dict['thal']}.0"] = 1

    df = pd.DataFrame([encoded])
    df = df.reindex(columns=model.feature_names_in_, fill_value=0)
    return df

st.set_page_config(page_title="تطبيق التنبؤ بأمراض القلب", page_icon="❤️")
st.title("❤️ تطبيق التنبؤ بأمراض القلب")

# واجهة إدخال البيانات بالعربي
age = st.number_input("العمر", 1, 120, 50)
sex = st.selectbox("الجنس", [0,1], format_func=lambda x: "ذكر" if x==1 else "أنثى")
cp = st.selectbox("نوع ألم الصدر (cp)", [1,2,3,4])
trestbps = st.number_input("ضغط الدم أثناء الراحة", 50, 300, 120)
chol = st.number_input("مستوى الكولسترول في الدم (mg/dl)", 50, 700, 200)
fbs = st.selectbox("سكر صائم > 120 (fbs)", [0,1])
restecg = st.selectbox("تخطيط القلب أثناء الراحة (restecg)", [0,1,2])
thalach = st.number_input("أقصى معدل نبض تم الوصول إليه", 30, 300, 150)
exang = st.selectbox("ذبحة صدرية بسبب المجهود (exang)", [0,1])
oldpeak = st.number_input("انخفاض ST (oldpeak)", 0.0, 10.0, 1.0, step=0.1)
slope = st.selectbox("ميل مقطع ST (slope)", [1,2,3])
ca = st.selectbox("عدد الأوعية الدموية الرئيسية (ca)", [0,1,2,3])
thal = st.selectbox("الثلاسيميا (thal)", [3,6,7])

raw_input = {
    "age":age,"sex":sex,"cp":cp,"trestbps":trestbps,"chol":chol,"fbs":fbs,
    "restecg":restecg,"thalach":thalach,"exang":exang,"oldpeak":oldpeak,
    "slope":slope,"ca":ca,"thal":thal
}

# زر التنبؤ
if st.button("تنبؤ"):
    X = encode_input(raw_input)
    pred = model.predict(X)[0]
    proba = model.predict_proba(X)[0]

    if pred == 1:
        st.error(f"⚠️ الموديل يتوقع أن المريض قد يكون لديه مرض قلب (احتمال = {proba[1]:.2f})")
    else:
        st.success(f"✅ الموديل يتوقع أن المريض من غير المرجح أن يكون عنده مرض قلب (احتمال = {proba[0]:.2f})")